### ISSUE TITLE
Too bright

### ISSUE THREAD

**Issue by MarkGhanz** [steel99xl/Mac-like-automatic-brightness#1]
It seems SensorToDisplayScale is way too much, locking the screen to its max brightness even in a completely dark room. I think it would be better to change it to 1. Even at 1 It can get decent brightness indoors.

**Comment by steel99xl** [comment]
What version of the framework laptop do you have?

**Comment by steel99xl** [comment]
No response

**Comment by josh1244** [comment]
I have 11th gen and it was the same for me. 1 fixed it, but I would like to decrease it a bit more.

**Comment by steel99xl** [comment]
you should be able to decrees the SensorToDisplayScale to have the screen be dimmer when compared to the default value.
Check the reported max brightness for your screen and light sensor. I would assume they would be the same as the 12th gens but idk

Also at least on 12th gen you cant have the brightness keys working with the sensor

**Comment by josh1244** [comment]
The values are correct and the same for the 11th. I was wondering if I could go less than one, say 0.75 or 0.5.

**Comment by steel99xl** [comment]
Yea but bash by default doesn't do floating point math. Thats really weird tho sense if you drop below a ratio of 23 you wont be able to achieve maximum screen brightness (assuming your sensor tops out at 3984)
