### ISSUE TITLE
Backlight turns off in total darkness

### ISSUE THREAD

**Issue by JeromeIsHere** [steel99xl/Mac-like-automatic-brightness#10]
Script seems to run perfectly on Framework 11th Gen until in complete darkness where the backlight turns off completely. Setting minimum brightness doesn't seem to affect this happening

**Comment by steel99xl** [comment]
Thank you, what did you set the minimum brightness to?

**Comment by JeromeIsHere** [comment]
010

**Comment by steel99xl** [comment]
Thank you.
When you get the chance can you try the new version and let me know if it at least helps with keeping the backlight on.

**Comment by JeromeIsHere** [comment]
That seems to have done the trick!

**Comment by steel99xl** [comment]
Thank you, feel free to let me know if you have any other issues
