### ISSUE TITLE
Use Environment Variable to select Framework Gen

### ISSUE THREAD

**Issue by miili** [steel99xl/Mac-like-automatic-brightness#5]
Select Framework profile by environment variable. These can be passed through the service file.

**Comment by steel99xl** [comment]
Thank you, but this is a shell script not a service
I don’t provide any files/configs to make it a service (if I did they would only be for runnit)

if you could provide the variables I could look in to adding/ addressing them

**Comment by miili** [comment]
Isn't there a `.service` file now? I can pitch a PR.

Thanks for the script and merry Christmas,

M

**Comment by Lazerbeak12345** [comment]
I'd be willing to provide an s6-rc service dir

**Comment by steel99xl** [comment]
Thank you, and yes as of now we are going to support it as a system service

**Comment by Lazerbeak12345** [comment]
As for the actual issue at hand - it should be possible to detect if it's a framework, and the exact model using information from the kernel and its modules. KDE can tell, so I'd imagine this tool can too.

**Comment by steel99xl** [comment]
You have and suggestions?
Also what exactly does it identify, cause just getting a vendor name from the bios is useless for knowing where sensors are located (I would need a look up table)

**Comment by Lazerbeak12345** [comment]
My idea is at the beginning of the script it uses vendor info & etc to determine the model. It then sets variables at the top, similar to the script for dell laptops. Setting these will be a one time thing per run.

EDIT: recent PR #7 moves the relevant variables to the top and got rid of the dell laptop script

**Comment by steel99xl** [comment]
Their is now a configuration part of the setup.sh scrip for the ambient light sensor
