### ISSUE TITLE
setup.sh destroys AutomaticBrightness.sh

### ISSUE THREAD

**Issue by matthiaswaechter** [steel99xl/Mac-like-automatic-brightness#8]
In the current version, performing executing setup.sh results in a disfunctional AutomaticBrightness.sh. It will alway reduce brightness to the lowest possible value. I believe there is something wrong with the awk line, but cannot figure this out.

**Comment by steel99xl** [comment]
Yea, awk was capturing "SensorToDisplayScale" when it need to capture "SensorToDisplayScale=" it should be fixed in the recent commit.
